services:
  mongodb:
    image: mongo:latest
    container_name: mongodb # Opcional, mas útil
    ports:
      - "27017:27017"
    restart: "on-failure"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # ESTE NOME DE USUÁRIO
      MONGO_INITDB_ROOT_PASSWORD: mongodb # ESTA SENHA
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh 'mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/store?authSource=admin --quiet'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build: .
    container_name: python-com-tdd
    ports:
      - "8000:8000"
    depends_on:
      - "mongodb"
    env_file:
      - .env.local
volumes:
  mongodb_data:
